const LOGIN_USER = {
  REQUEST: "LOGIN_USER_REQUEST",
  SUCCESS: "LOGIN_USER_SUCCEED",
  FAIL: "LOGIN_USER_FAIL",
  GET_INFO_REQUEST: "LOGIN_USER_GET_INFO_REQUEST",
  GET_INFO_SUCCESS: "LOGIN_USER_GET_INFO_SUCCESS",
  GET_INFO_FAIL: "LOGIN_USER_GET_INFO_FAIL",
};

const SHIPMENTS = {
  REQUEST: "SHIPMENTS_REQUEST",
  SUCCESS: "SHIPMEENTS_SUCCESS",
  FAIL: "SHIPMENTS_FAIL",
};

const SIDEBAR_STATE = {
  DESKTOP: "SIDEBAR_STATE_DESKTOP",
  MOBILE: "SIDEBAR_STATE_MOBILE",
  CLEAN: "SIDEBAR_STATE_CLEAN",
};

const PICKUP_POINTS = {
  ADD: "ADD_PICKUP_POINT",
  REMOVE: "REMOVE_PICKUP_POINT",
};

const DROPOFF_POINTS = {
  ADD: "ADD_DROPOFF_POINT",
  REMOVE: "REMOVE_DROPOFF_POINT",
};

export { LOGIN_USER, SIDEBAR_STATE, SHIPMENTS, PICKUP_POINTS, DROPOFF_POINTS };
