const LOGIN_USER = {
  REQUEST: "LOGIN_USER_REQUEST",
  SUCCESS: "LOGIN_USER_SUCCEED",
  FAIL: "LOGIN_USER_FAIL",
  GET_INFO_REQUEST: "LOGIN_USER_GET_INFO_REQUEST",
  GET_INFO_SUCCESS: "LOGIN_USER_GET_INFO_SUCCESS",
  GET_INFO_FAIL: "LOGIN_USER_GET_INFO_FAIL",
};

const SHIPMENTS = {
  REQUEST: "SHIPMENTS_REQUEST",
  SUCCESS: "SHIPMEENTS_SUCCESS",
  FAIL: "SHIPMENTS_FAIL",
};

const SIDEBAR_STATE = {
  DESKTOP: "SIDEBAR_STATE_DESKTOP",
  MOBILE: "SIDEBAR_STATE_MOBILE",
  CLEAN: "SIDEBAR_STATE_CLEAN",
};

const PICKUP_OPTIONS = {
  HANDLE_DRAWER: "HANDLE_DRAWER_PICKUP_OPTION",
  SELECT: "SELECT_PICKUP_OPTION",
  ADD: "ADD_PICKUP_OPTION",
  REMOVE: "REMOVE_PICKUP_OPTION",
};

const DROPOFF_OPTIONS = {
  HANDLE_DRAWER: "HANDLE_DRAWER_DROPOFF_OPTION",
  SELECT: "SELECT_DROPOFF_OPTION",
  DESELECT: "DESELECT_DROPOFF_OPTION",
  ADD: "ADD_DROPOFF_OPTION",
  EDIT: "EDIT_DROPOFF_OPTION",
  CANCEL_EDIT: "CANCEL_EDIT_DROPOFF_OPTION",
  UPDATE: "UPDATE_DROPOFF_OPTION",
  REMOVE: "REMOVE_DROPOFF_OPTION",
};

const GET_ONE_SHIPMENT = {
  REQUEST: "GET_ONE_SHIPMENT_REQUEST",
  SUCCESS: "GET_ONE_SHIPMENT_SUCCESS",
  FAIL: "GET_ONE_SHIPMENT_FAIL",
  REMOVE_PACKAGE: "GET_ONE_SHIPMENT_REMOVE_PACKAGE",
  ADD_PACKAGE: "GET_ONE_SHIPMENT_ADD_PACKAGE",
  UPDATE_PACKAGE: "GET_ONE_SHIPMENT_UPDATE_PACKAGE",
};

const VEHICLE = { SELECT: "SELECT_VEHICLE" };

export {
  LOGIN_USER,
  SIDEBAR_STATE,
  SHIPMENTS,
  DROPOFF_OPTIONS,
  PICKUP_OPTIONS,
  GET_ONE_SHIPMENT,
  VEHICLE,
};
